site_name: Porter

# as the mkdocs.yml is in the docs/configs/ subfolder, we need to set the docs_dir to '../'
docs_dir: '../'
site_dir: '../../site'

theme:
  name: readthedocs
  highlights: true
plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google


nav:
  - Home: index.md
  - High Level Concepts:
    - Core Concepts: core-concepts.md
    - Pipeline: porter-pipeline.md
    - Engines: porter-engines.md
    - Execution Modes: execution-modes.md
    - Governance:
        - Auditing: governance/auditing.md
        - Notifications: governance/notifications.md
        - Lineage: governance/lineage.md
  - Configuration Models:
    - Sources: models/sources.md
    - Targets: models/targets.md
    - Datasets:
        - File Dataset: models/datasets/file-dataset.md
        - Table Dataset: models/datasets/table-dataset.md
        - API Dataset: models/datasets/api-dataset.md
        - Stream Dataset: models/datasets/stream-dataset.md
    - Transformations: models/transformations.md
    - Validations: models/validations.md
  - CLI Reference: cli-reference.md
  - About:
    - License: about/license.md
    - Change Log: about/changelog.md
    - Contribute: about/contributing.md
