---
name: sample_pipeline
description: 'A Sample pipeline config'
source:
    name: sample_source

secrets_backend_config: '/Users/stallapalli/PycharmProjects/porter/example/sample_aws_sm_secrets_backend_config.yaml'
datasets:
    - name: dataset1
      file_path: '/sample/tmp/path/'
      file_type: 'csv'
      engine: 'duckdb'
      args:
          has_header: true
      on_dataset_missing:
          action: poll
          poll_interval: 60
          poll_count: 10
          post_poll_dataset_missing_action: error

targets:
  - name: sample_target
metadata:
    env: dev
    repo: https://github.com/myproject
