---
name: Generate docs

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, reopened, edited, synchronize]


jobs:
  runs-on: ubuntu-latest

  docs:
    steps:
      - name: Generate docs
        run: echo "Generating docs"
