---
name: Run PyTests

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, reopened, edited, synchronize]


jobs:
  runs-on: ubuntu-latest

  docs:
    steps:
      - name: Run PyTests
        run: echo "Running PyTests"
